name: Test and lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: clippy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        cargo install cargo2junit;
        cargo test --verbose -- -Z unstable-options --format json | cargo2junit > results.xml;
    - name: Upload test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        check_name: Test Results
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: results.xml
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
